-- MySQL Script generated by MySQL Workbench
-- Thu Jun 29 22:31:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resource_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `resource_management` ;

-- -----------------------------------------------------
-- Schema resource_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resource_management` DEFAULT CHARACTER SET utf8 ;
USE `resource_management` ;

-- -----------------------------------------------------
-- Table `resource_management`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Roles` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `decription` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Location` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(100) NULL,
  `province` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `municipality` VARCHAR(100) NULL,
  `brangay` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Users` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Users` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(60) NULL,
  `mname` VARCHAR(45) NULL,
  `lname` VARCHAR(100) NULL,
  `bday` DATE NULL,
  `gender` ENUM('M', 'F') NULL,
  `email` VARCHAR(150) NULL,
  `telno` VARCHAR(45) NULL,
  `celno` VARCHAR(45) NULL,
  `address_location` INT(11) NULL,
  `address` VARCHAR(200) NULL,
  `role_id` INT(11) NULL,
  `reported_to` INT(11) NULL,
  `status` ENUM('Active', 'NotActive') NULL,
  `enrolled_by` INT(11) NULL,
  `enrolled_date` DATETIME NOT NULL,
  `modified_by` INT(11) NULL,
  `modified_date` DATETIME NOT NULL,
  `Roles_id` INT NOT NULL,
  `Location_id` INT NOT NULL,
  `Location_Assigments_id` INT NOT NULL,
  `username` VARCHAR(90) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`, `Roles_id`, `Location_id`, `Location_Assigments_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Customers` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Customers` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(60) NULL,
  `mname` VARCHAR(45) NULL,
  `lname` VARCHAR(100) NULL,
  `bday` DATE NULL,
  `gender` ENUM('M', 'F') NULL,
  `email` VARCHAR(150) NULL,
  `telno` VARCHAR(45) NULL,
  `celno` VARCHAR(45) NULL,
  `address_location` INT(11) NULL,
  `address` VARCHAR(200) NULL,
  `status` ENUM('PROSPECT', 'REGULAR', 'BLOCKED') NULL,
  `enrolled_by` INT(11) NULL,
  `enrolled_date` DATETIME NOT NULL,
  `modified_by` INT(11) NULL,
  `modified_date` DATETIME NOT NULL,
  `Customer_Bussinesses_id` INT NOT NULL,
  `Location_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Customer_Bussinesses_id`, `Location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Customer_Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Customer_Organization` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Customer_Organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `title` VARCHAR(50) NULL,
  `description` VARCHAR(100) NULL,
  `address_location` INT NULL,
  `address` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `landline` VARCHAR(100) NULL,
  `mobile` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Location_Assigments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Location_Assigments` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Location_Assigments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `location_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Activity_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Activity_Type` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Activity_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `description` VARCHAR(255) NULL,
  `type` ENUM('Activity', 'Event') NULL DEFAULT 'Activity',
  `is_for_approval` ENUM('Y', 'N') NULL DEFAULT 'N',
  `is_teritorial` ENUM('Y', 'N') NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Events` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `description` VARCHAR(255) NULL,
  `customer_id` INT NULL,
  `customer_bussiness_id` INT NULL,
  `technician_id` INT NULL,
  `location_id` INT NULL,
  `address` VARCHAR(100) NULL,
  `is_approved` ENUM('Y', 'N') NULL DEFAULT 'N',
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `approved_by` INT NULL,
  `approved_date` DATETIME NULL,
  `enrolled_by` INT NULL,
  `enrolled_date` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_date` DATETIME NULL,
  `Activities_id` INT NOT NULL,
  `Activities_Activity_Type_id` INT NOT NULL,
  `Activities_Activity_Type_Location_id` INT NOT NULL,
  `Activities_Activity_Type_Location_Location_Assigments_id` INT NOT NULL,
  `Activities_Activity_Comments_id` INT NOT NULL,
  `Activities_Activity_Attachments_id` INT NOT NULL,
  `type_id` INT NULL,
  PRIMARY KEY (`id`, `Activities_id`, `Activities_Activity_Type_id`, `Activities_Activity_Type_Location_id`, `Activities_Activity_Type_Location_Location_Assigments_id`, `Activities_Activity_Comments_id`, `Activities_Activity_Attachments_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Activities` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `customer_id` INT NULL,
  `event_id` INT NULL,
  `description` VARCHAR(255) NULL,
  `technician_id` INT NULL,
  `location_id` INT NULL,
  `address` VARCHAR(100) NULL,
  `is_approved` ENUM('Y', 'N') NULL DEFAULT 'N',
  `approved_by` INT NULL,
  `approved_date` DATETIME NULL,
  `enrolled_by` INT NULL,
  `enrolled_date` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_date` DATETIME NULL,
  `Activity_Type_id` INT NOT NULL,
  `Activity_Type_Location_id` INT NOT NULL,
  `Activity_Type_Location_Location_Assigments_id` INT NOT NULL,
  `Activity_Comments_id` INT NOT NULL,
  `Activity_Attachments_id` INT NOT NULL,
  `type_id` INT NULL,
  PRIMARY KEY (`id`, `Activity_Type_id`, `Activity_Type_Location_id`, `Activity_Type_Location_Location_Assigments_id`, `Activity_Comments_id`, `Activity_Attachments_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Activity_Attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Activity_Attachments` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Activity_Attachments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NULL,
  `titile` VARCHAR(100) NULL,
  `source` VARCHAR(255) NULL,
  `type` ENUM('IMG', 'MAP', 'DOC') NULL,
  `is_deleted` ENUM('Y', 'N') NULL,
  `enrolled_by` INT NULL,
  `enrolled_date` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Activity_Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Activity_Comments` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Activity_Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NULL,
  `comments` VARCHAR(255) NULL,
  `commented_by` INT NULL,
  `commented_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Events_Custom_Fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Events_Custom_Fields` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Events_Custom_Fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NULL,
  `title` VARCHAR(100) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Company` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Description` TEXT NULL,
  `Address` TEXT NULL,
  `Contacts` TEXT NULL,
  `Title` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Notifications` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NULL,
  `event_id` INT NULL,
  `approver_id` INT NULL,
  `assigner_id` INT NULL,
  `notification_date` DATETIME NULL,
  `view_status` ENUM('Y', 'N') NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Menu` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `perent` INT NULL,
  `sort` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`Privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`Privileges` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`Privileges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `menuid` INT NOT NULL,
  `created_by` INT NULL,
  `created_date` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_management`.`PresetPrivileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_management`.`PresetPrivileges` ;

CREATE TABLE IF NOT EXISTS `resource_management`.`PresetPrivileges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleid` INT NOT NULL,
  `menuid` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
